services:
  - type: web
    name: rideshare-backend
    runtime: docker
    rootDir: .
    dockerfilePath: server/Dockerfile
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_BIN
        value: python3
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: OTP_EXPIRY
        value: 5
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: CLIENT_URL
        value: https://ride-share-app-eta.vercel.app
      - key: CLIENT_URLS
        value: https://ride-share-app-eta.vercel.app
